### ISSUE TITLE
Error with other modules

### ISSUE THREAD

**Issue by lordmicro** [PhalconEye/phalconeye#102]
According to https://github.com/PhalconEye/cms/commit/b2f00902074e857e9141d00f9c6ea6d3aeaaa177#commitcomment-8832739 , https://github.com/PhalconEye/cms/commit/6b5082490bc04387709882bc41af20acd5f68702#commitcomment-8832859 and https://github.com/PhalconEye/cms/commit/a5447e9eabaa2ff62182deb0b1ba9ad18035bbdc#commitcomment-8832866

**Comment by lantian** [comment]
Not actual. Thanks!
