### ISSUE TITLE
Problems at form.js

### ISSUE THREAD

**Issue by lordmicro** [PhalconEye/phalconeye#104]
Про баг. Если название элемента включает специальные символы - то скрипт не работает. Спец. символы указаны в документации: http://api.jquery.com/category/selectors/ .
В данный момент "Conditions" работает не очень правильно. Если делать вот такое сравнение: " a=1 && b=1 || a=2 && b=2 ", то оно отрабатывает непредсказуемо. Элемент "или" отрабатывает неверно.

About the bug. If the element name includes special characters - the script does not work. Spec. characters specified in the documentation: http://api.jquery.com/category/selectors/.
At the moment, "Conditions" does not work very well. If you make such a comparison here: "a = 1 && b = 1 || a = 2 && b = 2", then it fulfills unpredictable. Element "or" work out wrong.

Fix bug in accordance with: https://github.com/PhalconEye/cms/commit/92cb46d87d21716bbd3c8f53117e77f04befc616#commitcomment-9063462 , https://github.com/PhalconEye/cms/commit/92cb46d87d21716bbd3c8f53117e77f04befc616#commitcomment-9063483 and https://github.com/PhalconEye/cms/commit/45c865deef6367defde95918642760cf42e7edfc#commitcomment-9063544 .

Fix for "OR" according to https://github.com/PhalconEye/cms/commit/92cb46d87d21716bbd3c8f53117e77f04befc616#commitcomment-9063513

**Comment by lantian** [comment]
Fix applied in 0.5.0. Thanks!
