### ISSUE TITLE
Small updates at AdminUsers controller

### ISSUE THREAD

**Issue by lordmicro** [PhalconEye/phalconeye#105]
According to:
https://github.com/PhalconEye/cms/commit/beb6273235cb6c6ad08418806154102e27375c79#commitcomment-9084442
https://github.com/PhalconEye/cms/commit/beb6273235cb6c6ad08418806154102e27375c79#commitcomment-9084453
https://github.com/PhalconEye/cms/commit/beb6273235cb6c6ad08418806154102e27375c79#commitcomment-9084454
https://github.com/PhalconEye/cms/commit/beb6273235cb6c6ad08418806154102e27375c79#commitcomment-9084455

**Comment by lantian** [comment]
Thanks, applied on all navigations.
