### ISSUE TITLE
Browse server button does not use the specified baseurl from development config file

### ISSUE THREAD

**Issue by HIMISOCOOL** [PhalconEye/phalconeye#107]
On the manage screen when you edit an HTML block, using the text editor when you click the image button on the toolbar, on pressing the browse server button the window that opens' url is not correctly formatted (see the images)

note I am using the development config

The image specification view
![imageview](https://cloud.githubusercontent.com/assets/1725300/5627275/e2a8f382-95fa-11e4-8743-225b7dfc6943.PNG)

press browse server

The window that pops out with the wrong url 
![pydio wrong url](https://cloud.githubusercontent.com/assets/1725300/5627277/e2b76c6e-95fa-11e4-89b4-e6c92f59faf7.PNG)
the right url
![pydio right url](https://cloud.githubusercontent.com/assets/1725300/5627276/e2b613b4-95fa-11e4-994d-3554cc3c85b0.PNG)

but this is from ck editor, changing all the urls from the config.js file to have 
`../../../` seems to work for me but might not work for everyone
![ckeditor config js](https://cloud.githubusercontent.com/assets/1725300/5627571/dadb1370-95fe-11e4-8811-973705d8c729.PNG)

futhermore the image that was selected from Pydio afterwards is incorrect
it gives the file /files/image.jpg but it needs to be ../files/image.jpg to work

also ckeditor 4.3.2 is not working correctly for me on Google Chrome    39.0.2171.95 (Official Build) or IE11, 4.4.6+ works fine though.

I'm not sure of the Etiquette around this on github, whether or not its obnoxious to make many reports cause there's 2 maybe 3 issues here.

**Comment by lantian** [comment]
Ok, thanks very much, i will double check it!

**Comment by HIMISOCOOL** [comment]
in the future when I find multiple things should I make separate issues?

**Comment by lantian** [comment]
You can leave them in one ticket if thay related to each other, otherwise - separated.

**Comment by lantian** [comment]
Thanks, fixed in 0.5.0
