### ISSUE TITLE
Trying to install, whats this mean ?

### ISSUE THREAD

**Issue by darrencain** [PhalconEye/phalconeye#112]
Warning: require_once(/home/USER/public_html/app/engine/Config.php): failed to open stream: No such file or directory in /home/USER/public_html/phalconeye/index.php on line 57

Fatal error: require_once(): Failed opening required '/home/USER/public_html/app/engine/Config.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/USER/public_html/phalconeye/index.php on line 57

Config.php is uploaded, so don't know why it cant open

Version 0.4.1

**Comment by lantian** [comment]
Hi, you have strange pathes^
/home/USER/public_html/app/engine/Config.php
/home/USER/public_html/phalconeye/index.php

phalconeye is copy of public dir with htaccess, etc?

**Comment by darrencain** [comment]
Yep I've moved everything to the root of the public_html folder still get the error

Warning: require_once(/home/tulexnet/app/engine/Config.php): failed to open stream: No such file or directory in /home/tulexnet/public_html/index.php on line 57

Fatal error: require_once(): Failed opening required '/home/tulexnet/app/engine/Config.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/tulexnet/public_html/index.php on line 57

**Comment by lantian** [comment]
are you sure that file '/home/tulexnet/app/engine/Config.php'  exists and webserver can access it (user rights, etc)?

**Comment by darrencain** [comment]
yep defiantly on the web-server with file permission 0644

**Comment by lantian** [comment]
If you will have new questions - feel free to reopen.
