### ISSUE TITLE
0.5 - Fix Travis Tests

### ISSUE THREAD

**Issue by WooDzu** [PhalconEye/phalconeye#120]
Output from Travis CI IS:

```
$ pyrus install pear/PHP_CodeSniffer
rbenv: pyrus: command not found
The `pyrus' command exists in these PHP versions:
  5.3.29
  5.3.3
  5.5.9
  5.6.13
The command "pyrus install pear/PHP_CodeSniffer" failed and exited with 127 during .
```
Should probably update the tests to use PHP 5.5.9 and 5.6.13.

**Comment by lantian** [comment]
I will update it up to PHP 7.0.11, 0.5.0 will work with it.

**Comment by lantian** [comment]
Fixed in 0.5.0. https://travis-ci.org/PhalconEye/phalconeye/builds/170123207 Thanks!

**Comment by sergeyklay** [comment]
@lantian Could you please sort out with this
![screenshot at oct 24 16-12-28](https://cloud.githubusercontent.com/assets/1256298/19647031/f1cf3866-9a04-11e6-9491-17917041f4a9.png)

**Comment by lantian** [comment]
This is only master raleted. Will be updated when 0.5.0 becomes master. No need for now, anyway it is broken there.
