### ISSUE TITLE
URL for repo description is invalid

### ISSUE THREAD

**Issue by sergeyklay** [PhalconEye/phalconeye#131]
> PhalconEye CMS Powered by Phalcon Framework http://phalconeye.com

**Comment by lantian** [comment]
You mean that domain phalconeye.com doesn't exist anymore or that here must be a link to phalconphp website?

**Comment by sergeyklay** [comment]
In my opinion here must be a valid URL. It would be nice to link to the working demo. 

```
curl -I http://phalconeye.com
HTTP/1.1 302 Found
Server: nginx
Date: Sun, 04 Dec 2016 18:47:25 GMT
Content-Length: 11
Connection: keep-alive
location: http://survey-winner.net
```

A good temporary solution is to link to the releases: https://github.com/PhalconEye/phalconeye/releases

**Comment by lantian** [comment]
It was my domain =), I had problems with payment and lost it =(. Will try to get it back in future. 

Removed from the description. Thanks

**Comment by sergeyklay** [comment]
Something like: [phalcon[eye].io](http://phalconeye.io), [phalconp[eye].site](http://phalconeye.site), [phalcon[eye].tech](http://phalconeye.tech) still free I guess :)

**Comment by lantian** [comment]
Yeaa... but .com was the best =). I will think about other domains.

**Comment by Jurigag** [comment]
io maybe ?
