### ISSUE TITLE
Mutlilanguage on url

### ISSUE THREAD

**Issue by macagoraga** [PhalconEye/phalconeye#86]
For follow SEO best practice, do you think to add language code on url?
Example:
www.example.com/en/login => load login in english
www.example.com/de/login => load login in german
www.example.com/login => redirect to main language (www.example.com/en/login)

phalcon routing example:

$router = new Phalcon\Mvc\Router(false);
$router->add('/{language:[a-z]+}/:controller/:action/:params', array(
    'controller' => 2,
    'action' => 3,
    'params' => 4
));

Thanks!

**Comment by lantian** [comment]
Implemented in 0.5.0. Thanks!
