### ISSUE TITLE
Phalcon\Assets\Exception from outputCss() off initial install

### ISSUE THREAD

**Issue by HIMISOCOOL** [PhalconEye/phalconeye#88]
Phalcon\Assets\Exception: Resource 'E:\Xammp\htdocs\PhalconEye\public\external\jquery\jquery-ui.css' have the same source and target paths 
E:\Xammp\htdocs\PhalconEye\app\engine\Asset\Manager.php (355)

I just followed the install process and this is the result

Using Xammp v3.2.1
PHP Version => 5.5.15
Phalcon Framework => enabled
Phalcon Version => 1.3.4

and I used the 0.4.1 zip from the website's download page

**Comment by simonhochrein** [comment]
I am having the same issue.  The front-end works by setting debug to false.  But then the backend admin area has same issue.  I am running Phalcon 2.0 on ubuntu.

Here is the error:
 Phalcon\Assets\Exception: Resource '/var/www/cms/public/external/bootstrap/css/bootstrap.min.css' have the same source and target paths
/var/www/cms/app/engine/Asset/Manager.php (359)
#0	Phalcon\Assets\Manager->output(Object(Phalcon\Assets\Collection), Array(0 => Phalcon\Tag, 1 => stylesheetLink), css)
#1	Phalcon\Assets\Manager->outputCss(css)
/var/www/cms/app/engine/Asset/Manager.php (359)

Any ideas?

**Comment by lantian** [comment]
Sorry, phalcon 2 isn't supported currently. It has some changes that must be handled properly.

**Comment by ipfedor** [comment]
error "have the same source and target paths"
compile 1.3.4 for windows, problem resolved on main page, and save on admin page
wtf?

**Comment by lantian** [comment]
> Thanks, I have reported an issue of version requirement #94
> This bug for 1.3.4 also will be fixed in next release.

There is a problem for 1.3.4 version.

**Comment by ipfedor** [comment]
version 1.3.2 work fine.

**Comment by lantian** [comment]
Yep, in feature I will restrict PhalconEye only for one version of phalcon. Coz any new version comes with different problems.

**Comment by HIMISOCOOL** [comment]
Is 0.5 targeting phalcon 2? I know both aren't even finalIzed yet but still.

**Comment by lantian** [comment]
Yes, at moment of release - PhalconEye will support latest Phalcon

**Comment by xaero7** [comment]
Has it fixed the problem?
I got the same porblem!
My env:
ubuntu 14
apache
php 5.5
phalcon 1.3.4

**Comment by HIMISOCOOL** [comment]
you will have to compile an older version of phalcon from source as @lantian said,
>new version comes with different problems.

1.3.3 needs a fix for the users view to work correctly so 1.3.2 or 1.3.1 would be a much better bet.

>git clone https://github.com/phalcon/cphalcon.git
>cd /path/to/phalcon/
>git checkout -f 1.3.3
(or whatever version you want
and compile it on linux with the instructions on this page http://phalconphp.com/en/download

**Comment by mycrom** [comment]
You can make a few quick corrections to get this working right now with phalcon 1.3.4 before a better fix can be put in place. Check out https://github.com/PhalconEye/cms/pull/109

**Comment by ve3** [comment]
same error!

Phalcon\Assets\Exception: Resource 'C:\Users\mr.v\my-sites\github\phalconeye\public\external\jquery\jquery-ui.css' have the same source and target paths
C:\Users\mr.v\my-sites\github\phalconeye\app\engine\Asset\Manager.php (355)

Just installed and bang! error page.

**Comment by zhanghengwh15** [comment]
Phalcon\Assets\Exception: Resource 'E:\php\phalcon\workstation\cms-master\public\external\jquery\jquery-ui.css' have the same source and target paths 
E:\php\phalcon\workstation\cms-master\app\engine\Asset\Manager.php (355)
me too

**Comment by lantian** [comment]
As mentioned before - this is a problem with 1.3.4 and above versions.

**Comment by lantian** [comment]
This issue was fixed in 0.5.0 branch. (phalcon 3.0.1)
