### ISSUE TITLE
Language Translation Grid condition problem

### ISSUE THREAD

**Issue by lordmicro** [PhalconEye/phalconeye#92]
According to https://github.com/PhalconEye/cms/commit/6b5082490bc04387709882bc41af20acd5f68702#commitcomment-8517322 and https://github.com/PhalconEye/cms/commit/f7a974a7e6c40f63ebea205f477ee9f46338b9fc#commitcomment-8517342

**Comment by lantian** [comment]
Thanks, applied in 0.5.0
