### ISSUE TITLE
Problem of updating the grid after saving in a modal window editing

### ISSUE THREAD

**Issue by lordmicro** [PhalconEye/phalconeye#98]
Hello. Excuse me, but my text is written in Russian. Translated into English below.

Здравствуйте.
Проблема в интерфейсе редактирования переводов фраз. После нажатия "Изменить" и в открывшемся модальном окне нажать "Сохранить". После этого происходят баги сетки:
1) Не работает фильтр - фильтруешь - а он после загрузки фильтрованных данных, сбрасывает до предыдущего состояния сетки.
2) Таблица должна перезагружаться, т.к. после сохранения данные на странице уже не актуальны.
У меня нет полноценного решения проблемы.
Можно изменить файл "app\modules\Core\Assets\js\widgets\modal.js" так.
Было:

``` javascript
modalObject.on('hidden.bs.modal', function () {
    PhalconEye.core.hideLoadingStage();
});
```

Стало:

``` javascript
modalObject.on('hidden.bs.modal', function () {
    PhalconEye.core.hideLoadingStage();
    PhalconEye.widget.grid.load();
});
```

Тогда, описанная выше проблема решается, но появляется одна несущественная - после сохранения сетка загружается три раза вместо одного.

Hello.
Problem in editing interface translations of phrases. After clicking "Edit" to open the modal window to click "Save." After that there is a grid bugs:
1) Do not filter works - filtruesh - and he after loading the filtered data is reset to the previous state of the grid.
2) The table must reboot because after saving the data on the page is no longer relevant.
I do not have a complete solution of the problem.
You can change the file "app\modules\Core\Assets\js\widgets\modal.js" so.
It was:

``` javascript
modalObject.on('hidden.bs.modal', function () {
    PhalconEye.core.hideLoadingStage();
});
```

It became:

``` javascript
modalObject.on('hidden.bs.modal', function () {
    PhalconEye.core.hideLoadingStage();
    PhalconEye.widget.grid.load();
});
```

Then, the above-described problem is solved, but there is one insignificant - after saving the grid is loaded three times instead of one.

**Comment by lantian** [comment]
Thanks. Implemented grid update on modal submit.
But first case (with filtering) was not able to reproduse, maybe it was fixed already. Fill free to reopen if not fixed.
